import SwiftUI

public extension ArtPalette {
    static let allName: String = "Lego Full"
    static let all: Palette = Palette(name: allName, colors: allColors, names: allColorNames)
    
    // Full/All color palette
    private static let allColorNames: [String] = [ "black", "blue", "green", "darkTurquoise", "red", "darkPink", "brown", "lightGray", "darkGray", "lightBlue", "brightGreen", "lightTurquoise", "salmon", "pink", "yellow", "white", "lightGreen", "lightYellow", "tan", "lightViolet", "purple", "darkBlueViolet", "orange", "magenta", "lime", "darkTan", "brightPink", "mediumLavender", "lavender", "veryLightOrange", "lightPurple", "reddishBrown", "lightBluishGray", "darkBluishGray", "mediumBlue", "mediumGreen", "lightPink", "lightFlesh", "milkyWhite", "metallicSilver", "metallicGreen", "metallicGold", "mediumDarkFlesh", "darkPurple", "darkFlesh", "royalBlue", "flesh", "lightSalmon", "violet", "blueViolet", "mediumLime", "aqua", "lightLime", "lightOrange", "copper", "metalBlue", "veryLightBluishGray", "yellowishGreen", "flatDarkGold", "flatSilver", "pearlLightGray", "pearlLightGold", "pearlDarkGray", "pearlVeryLightGray", "pearlWhite", "brightLightOrange", "brightLightBlue", "rust", "brightLightYellow", "skyBlue", "darkBlue", "darkGreen", "pearlGold", "darkBrown", "maerskBlue", "darkRed", "darkAzure", "mediumAzure", "lightAque", "oliveGreen", "sandRed", "mediumDarkPink", "earthOrange", "sandPurple", "sandGreen", "sandBlue", "fabulandBrown", "mediumOrange", "darkOrange", "veryLightGray", "mediumViolet", "reddishLilac", "coral", "vibrantYellow", "chromeGold", "chromeSilver", "chromeAntiqueBrass", "chromeBlue", "chromeGreen", "chromePink", "chromeBlack", "speckleBlackSilver", "speckleBlackGold", "speckleBlackCopper", "speckleDBGraySilver" ];
    
    private static let allColors: [ColorType] = [black, blue, green, darkTurquoise, red, darkPink, brown, lightGray, darkGray, lightBlue, brightGreen, lightTurquoise, salmon, pink, yellow, white, lightGreen, lightYellow, tan, lightViolet, purple, darkBlueViolet, orange, magenta, lime, darkTan, brightPink, mediumLavender, lavender, veryLightOrange, lightPurple, reddishBrown, lightBluishGray, darkBluishGray, mediumBlue, mediumGreen, lightPink, lightFlesh, milkyWhite, metallicSilver, metallicGreen, metallicGold, mediumDarkFlesh, darkPurple, darkFlesh, royalBlue, flesh, lightSalmon, violet, blueViolet, mediumLime, aqua, lightLime, lightOrange, copper, metalBlue, veryLightBluishGray, yellowishGreen, flatDarkGold, flatSilver, pearlLightGray, pearlLightGold, pearlDarkGray, pearlVeryLightGray, pearlWhite, brightLightOrange, brightLightBlue, rust, brightLightYellow, skyBlue, darkBlue, darkGreen, pearlGold, darkBrown, maerskBlue, darkRed, darkAzure, mediumAzure, lightAque, oliveGreen, sandRed, mediumDarkPink, earthOrange, sandPurple, sandGreen, sandBlue, fabulandBrown, mediumOrange, darkOrange, veryLightGray, mediumViolet, reddishLilac, coral, vibrantYellow, chromeGold, chromeSilver, chromeAntiqueBrass, chromeBlue, chromeGreen, chromePink, chromeBlack, speckleBlackSilver, speckleBlackGold, speckleBlackCopper, speckleDBGraySilver];
    
}
