import SwiftUI

public extension ArtPalette {
    static let allName: String = "Lego Full"
    static let all: Palette = Palette(name: allName, colors: allColors)
    
    // Full/All color palette
    private static let allColors: [ArtColor] = [
        .init(Black, black),
        .init(Blue, blue), 
            .init(Green, green), 
            .init(DarkTurquoise, darkTurquoise), 
            .init(Red, red), 
            .init(DarkPink, darkPink), 
            .init(Brown, brown), 
            .init(LightGray, lightGray), 
            .init(DarkGray, darkGray), 
            .init(LightBlue, lightBlue), 
            .init(BrightGreen, brightGreen), 
            .init(LightTurquoise, lightTurquoise), 
            .init(Salmon, salmon), 
            .init(Pink, pink), 
            .init(Yellow, yellow), 
            .init(White, white),
        .init(LightGreen, lightGreen), 
            .init(LightYellow, lightYellow), 
            .init(Tan, tan), 
            .init(LightViolet, lightViolet), 
            .init(Purple, purple), 
            .init(DarkBlueViolet, darkBlueViolet), 
            .init(Orange, orange), 
            .init(Magenta, magenta), 
            .init(Lime, lime), 
            .init(DarkTan, darkTan), 
            .init(BrightPink, brightPink), 
            .init(MediumLavender, mediumLavender),
        .init(Lavender, lavender), 
            .init(VeryLightOrange, veryLightOrange), 
            .init(LightPurple, lightPurple),
                .init(ReddishBrown, reddishBrown), 
        .init(LightBluishGray, lightBluishGray), 
        .init(DarkBluishGray, darkBluishGray), 
        .init(MediumBlue, mediumBlue), 
        .init(MediumGreen, mediumGreen), 
        .init(LightPink, lightPink), 
        .init(LightFlesh, lightFlesh), 
        .init(MilkyWhite, milkyWhite), 
        .init(MetallicSilver, metallicSilver), 
        .init(MetallicGreen, metallicGreen), 
        .init(MetallicGold, metallicGold), 
        .init(MediumDarkFlesh, mediumDarkFlesh), 
        .init(DarkPurple, darkPurple), 
        .init(DarkFlesh, darkFlesh), 
        .init(RoyalBlue, royalBlue), 
        .init(Flesh, flesh), 
        .init(LightSalmon, lightSalmon), 
        .init(Violet, violet), 
        .init(BlueViolet, blueViolet), 
        .init(MediumLime, mediumLime), 
        .init(Aqua, aqua), 
        .init(LightLime, lightLime), 
        .init(LightOrange, lightOrange), 
        .init(Copper, copper), 
        .init(MetalBlue, metalBlue), 
        .init(VeryLightBluishGray, veryLightBluishGray), 
        .init(YellowishGreen, yellowishGreen), 
        .init(FlatDarkGold, flatDarkGold), 
        .init(FlatSilver, flatSilver), 
        .init(PearlLightGray, pearlLightGray), 
        .init(PearlLightGold, pearlLightGold), 
        .init(PearlDarkGray, pearlDarkGray), 
        .init(PearlVeryLightGray, pearlVeryLightGray), 
        .init(PearlWhite, pearlWhite), 
        .init(BrightLightOrange, brightLightOrange), 
        .init(BrightLightBlue, brightLightBlue), 
        .init(Rust, rust), 
        .init(BrightLightYellow, brightLightYellow), 
        .init(SkyBlue, skyBlue), 
        .init(DarkBlue, darkBlue), 
        .init(DarkGreen, darkGreen), 
        .init(PearlGold, pearlGold), 
        .init(DarkBrown, darkBrown), 
        .init(MaerskBlue, maerskBlue), 
        .init(DarkRed, darkRed), 
        .init(DarkAzure, darkAzure), 
        .init(MediumAzure, mediumAzure), 
        .init(LightAqua, lightAqua), 
        .init(OliveGreen, oliveGreen), 
        .init(SandRed, sandRed), 
        .init(MediumDarkPink, mediumDarkPink), 
        .init(EarthOrange, earthOrange), 
        .init(SandPurple, sandPurple), 
        .init(SandGreen, sandGreen), 
        .init(SandBlue, sandBlue), 
        .init(FabulandBrown, fabulandBrown), 
        .init(MediumOrange, mediumOrange), 
        .init(DarkOrange, darkOrange), 
        .init(VeryLightGray, veryLightGray), 
        .init(MediumViolet, mediumViolet), 
        .init(ReddishLilac, reddishLilac), 
        .init(Coral, coral),
        .init(VibrantYellow, vibrantYellow), 
        .init(ChromeGold, chromeGold), 
        .init(ChromeSilver, chromeSilver), 
        .init(ChromeAntiqueBrass, chromeAntiqueBrass), 
        .init(ChromeBlue, chromeBlue), 
        .init(ChromeGreen, chromeGreen), 
        .init(ChromePink, chromePink), 
        .init(ChromeBlack, chromeBlack), 
//        .init(SpeckleBlackSilver, speckleBlackSilver), 
//        .init(SpeckleBlackGold, speckleBlackGold), 
//        .init(SpeckleBlackCopper, speckleBlackCopper), 
//        .init(SpeckleDBGraySilver, speckleDBGraySilver)
                
    ];
       
}
